// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StringFetcher.Data;

#nullable disable

namespace StringFetcher.Migrations
{
    [DbContext(typeof(StringsDbContext))]
    partial class StringsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StringFetcher.Data.StringEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StringsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quote = "This is random string #1"
                        },
                        new
                        {
                            Id = 2,
                            Quote = "This is random string #2"
                        },
                        new
                        {
                            Id = 3,
                            Quote = "This is random string #3"
                        },
                        new
                        {
                            Id = 4,
                            Quote = "This is random string #4"
                        },
                        new
                        {
                            Id = 5,
                            Quote = "This is random string #5"
                        },
                        new
                        {
                            Id = 6,
                            Quote = "This is random string #6"
                        },
                        new
                        {
                            Id = 7,
                            Quote = "This is random string #7"
                        },
                        new
                        {
                            Id = 8,
                            Quote = "This is random string #8"
                        },
                        new
                        {
                            Id = 9,
                            Quote = "This is random string #9"
                        },
                        new
                        {
                            Id = 10,
                            Quote = "This is random string #10"
                        },
                        new
                        {
                            Id = 11,
                            Quote = "This is random string #11"
                        },
                        new
                        {
                            Id = 12,
                            Quote = "This is random string #12"
                        },
                        new
                        {
                            Id = 13,
                            Quote = "This is random string #13"
                        },
                        new
                        {
                            Id = 14,
                            Quote = "This is random string #14"
                        },
                        new
                        {
                            Id = 15,
                            Quote = "This is random string #15"
                        },
                        new
                        {
                            Id = 16,
                            Quote = "This is random string #16"
                        },
                        new
                        {
                            Id = 17,
                            Quote = "This is random string #17"
                        },
                        new
                        {
                            Id = 18,
                            Quote = "This is random string #18"
                        },
                        new
                        {
                            Id = 19,
                            Quote = "This is random string #19"
                        },
                        new
                        {
                            Id = 20,
                            Quote = "This is random string #20"
                        },
                        new
                        {
                            Id = 21,
                            Quote = "This is random string #21"
                        },
                        new
                        {
                            Id = 22,
                            Quote = "This is random string #22"
                        },
                        new
                        {
                            Id = 23,
                            Quote = "This is random string #23"
                        },
                        new
                        {
                            Id = 24,
                            Quote = "This is random string #24"
                        },
                        new
                        {
                            Id = 25,
                            Quote = "This is random string #25"
                        },
                        new
                        {
                            Id = 26,
                            Quote = "This is random string #26"
                        },
                        new
                        {
                            Id = 27,
                            Quote = "This is random string #27"
                        },
                        new
                        {
                            Id = 28,
                            Quote = "This is random string #28"
                        },
                        new
                        {
                            Id = 29,
                            Quote = "This is random string #29"
                        },
                        new
                        {
                            Id = 30,
                            Quote = "This is random string #30"
                        },
                        new
                        {
                            Id = 31,
                            Quote = "This is random string #31"
                        },
                        new
                        {
                            Id = 32,
                            Quote = "This is random string #32"
                        },
                        new
                        {
                            Id = 33,
                            Quote = "This is random string #33"
                        },
                        new
                        {
                            Id = 34,
                            Quote = "This is random string #34"
                        },
                        new
                        {
                            Id = 35,
                            Quote = "This is random string #35"
                        },
                        new
                        {
                            Id = 36,
                            Quote = "This is random string #36"
                        },
                        new
                        {
                            Id = 37,
                            Quote = "This is random string #37"
                        },
                        new
                        {
                            Id = 38,
                            Quote = "This is random string #38"
                        },
                        new
                        {
                            Id = 39,
                            Quote = "This is random string #39"
                        },
                        new
                        {
                            Id = 40,
                            Quote = "This is random string #40"
                        },
                        new
                        {
                            Id = 41,
                            Quote = "This is random string #41"
                        },
                        new
                        {
                            Id = 42,
                            Quote = "This is random string #42"
                        },
                        new
                        {
                            Id = 43,
                            Quote = "This is random string #43"
                        },
                        new
                        {
                            Id = 44,
                            Quote = "This is random string #44"
                        },
                        new
                        {
                            Id = 45,
                            Quote = "This is random string #45"
                        },
                        new
                        {
                            Id = 46,
                            Quote = "This is random string #46"
                        },
                        new
                        {
                            Id = 47,
                            Quote = "This is random string #47"
                        },
                        new
                        {
                            Id = 48,
                            Quote = "This is random string #48"
                        },
                        new
                        {
                            Id = 49,
                            Quote = "This is random string #49"
                        },
                        new
                        {
                            Id = 50,
                            Quote = "This is random string #50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
